#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-$(CONFIG_VIDEO_FB_IMX6)   +=  imx-fbdev.o
obj-$(CONFIG_SDK_HDMI_ZYNQ)   +=  zynq7sdk_hdmi.o

# end of file
