#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.12.21
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+= term_core.o
obj-y	+= term_task.o

obj-y	+= cmd/

# end of file
