#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.11.16
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

lib-y	+=  libfatfs.a
lib-y	+=  liblvgl.a
lib-y	+=  liblwip.a

# end of file
