#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.11.16
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

LIB_CUR_PATH	:=	$(EXT_LIB_DIRS)

inc-y	+=	$(LIB_CUR_PATH)/lwip/port
inc-y	+=	$(LIB_CUR_PATH)/lwip/src/include

# end of file
