#
# Makefile
#
# File Name:   Makefile
# Author:      Yang Yujun
# E-mail:      <yujiantianhu@163.com>
# Created on:  2024.04.12
#
# Copyright (c) 2024   Yang Yujun <yujiantianhu@163.com>
#

obj-y	+=	fwk_inet.o
obj-y	+=	fwk_netdev.o
obj-y	+=	fwk_network.o
obj-y	+=	fwk_skbuff.o

obj-y	+=	fwk_lwip.o

# end of file
